name: Build

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache 
        uses: Swatinem/rust-cache@v2.2.0
        with:
          cache-on-failure: "true"
      - name: Build
        run: cargo build --release --verbose
