name: CI

on:
  push:
    branches:
      ["main"]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  integration:
    uses: simple0x47/organization/.github/workflows/integration.yml@main
  release:
    needs: integration
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout definition provider
      uses: actions/checkout@v3
    - name: Cache 
      uses: Swatinem/rust-cache@v2.2.0
      with:
        cache-on-failure: "true"
    - name: Build
      run: cargo build --release
    - name: Create release tag
      id: create_release_tag
      run: |
        echo "tag_name=inc.$GITHUB_RUN_NUMBER" >> $GITHUB_OUTPUT
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_RELEASE_TOKEN }}
      with:
        tag_name: ${{ steps.create_release_tag.outputs.tag_name }}
        release_name: ${{ format('Release {0}', steps.create_release_tag.outputs.tag_name) }}
        body: ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false
    - name: Upload executable
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_RELEASE_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/release/cooplan-organization
        asset_name: cooplan-organization
        asset_content_type: application/x-elf
    - name: Upload config.json
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_RELEASE_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./config.json
        asset_name: config.json
        asset_content_type: application/json
    - name: Upload api.json
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_RELEASE_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./api.json
        asset_name: api.json
        asset_content_type: application/json
